// Package report renders a ledger for people to read.
package report

import (
	"fmt"
	"io"
	"math"
	"sort"
	"strconv"
	"strings"

	"github.com/ppapapetrou76/oss-chronicle/internal/ledger"
)

// Markdown writes the ledger as a GitHub-flavored Markdown summary listing the top people.
// serverURL is the GitHub web address profile links point to.
func Markdown(w io.Writer, res ledger.Result, top int, serverURL string) error {
	serverURL = strings.TrimSuffix(serverURL, "/")
	var b strings.Builder
	fmt.Fprintf(&b, "## Contribution ledger: %s\n\n", res.Repository)
	fmt.Fprintf(&b, "%s to %s · %s pull requests with activity · default branch `%s`\n\n", res.From, res.To, num(res.PullRequests), res.DefaultBranch)

	t := res.Totals
	b.WriteString("| PRs landed | PRs reviewed | with feedback | Comments | Merges | Triage closes | Maintenance |\n")
	b.WriteString("|---:|---:|---:|---:|---:|---:|---:|\n")
	fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s | %s |\n\n",
		num(t.Landed), num(t.Reviewed), num(t.ReviewedWithFeedback), num(t.Commented), num(t.Merged), num(t.Triaged), num(t.Maintenance))

	people := res.People
	if top > 0 && len(people) > top {
		people = people[:top]
	}
	fmt.Fprintf(&b, "### People (top %d of %d)\n\n", len(people), len(res.People))
	b.WriteString("| # | Contributor | Total | Landed | Reviewed | Comments | Merges | Triage | Maintenance | Authoring weight | Reviewing weight |\n")
	b.WriteString("|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n")
	for i, p := range people {
		fmt.Fprintf(&b, "| %d | [%s](%s/%s) | **%s** | %s | %s | %s | %s | %s | %s | %s | %s |\n", i+1, p.Login, serverURL, p.Login,
			num(p.Total), num(p.Landed), num(p.Reviewed), num(p.Commented), num(p.Merged), num(p.Triaged), num(p.Maintenance),
			dec(p.AuthoringWeight), dec(p.ReviewingWeight))
	}

	if sz := res.Size; len(sz.Buckets) > 0 {
		b.WriteString("\n### Size of landed PRs\n\n| Size | Counted lines | Weight | PRs |\n|---|---|---:|---:|\n")
		lower := 0.0
		for _, bk := range sz.Buckets {
			lines := fmt.Sprintf("over %s", dec(lower))
			if bk.Max != nil {
				lines = fmt.Sprintf("%s–%s", dec(lower), dec(*bk.Max))
				lower = *bk.Max
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n", bk.Name, lines, dec(bk.Weight), num(bk.Landed))
		}
		if sz.ChangedLines > 0 {
			share := math.Round(1000*float64(sz.ExcludedLines)/float64(sz.ChangedLines)) / 10
			fmt.Fprintf(&b, "\n%s%% of the lines changed by landed PRs are in generated, vendored or lock files and are not counted.", dec(share))
		}
		if sz.Unsized > 0 {
			fmt.Fprintf(&b, " %s landed PRs have no file data and carry no weight.", num(sz.Unsized))
		}
		b.WriteString("\n")
	}

	writeComponents(&b, res, serverURL)

	if len(res.Dropped) > 0 {
		b.WriteString("\n### Left out\n\n| Activity | Count |\n|---|---:|\n")
		for _, d := range res.Dropped {
			label := d.Label
			if d.Maintenance {
				label += " (credited as maintenance)"
			}
			fmt.Fprintf(&b, "| %s | %s |\n", label, num(d.Count))
		}
	}
	b.WriteString("\n<sub>Total = PRs landed + PRs reviewed + comments + merges + triage closes. Maintenance (reviews, merges and closes on backport, dependency and bot PRs) is shown separately. Authoring weight sums the size weights of a person's landed PRs; reviewing weight sums the weights of the PRs they reviewed, ")
	fmt.Fprintf(&b, "multiplied by %s when the review left feedback. ", dec(res.Size.ReviewFeedbackMultiple))
	b.WriteString("Each PR belongs to the component where most of its counted lines changed. A response is a review, comment, merge or close by anyone but the author and bots. Generated by oss-chronicle.</sub>\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// waitingListed is how many unanswered PRs the summary lists.
const waitingListed = 10

func writeComponents(b *strings.Builder, res ledger.Result, serverURL string) {
	if len(res.Components) == 0 {
		return
	}
	b.WriteString("\n### Components\n\n")
	b.WriteString("| Component | PRs landed | Authors | Reviewers | Top reviewer | People doing half the reviews | Median first response | Median time to merge | Waiting for a response |\n")
	b.WriteString("|---|---:|---:|---:|---|---:|---:|---:|---:|\n")
	for _, c := range res.Components {
		top := "–"
		if c.Reviews > 0 {
			top = pct(c.TopReviewerShare)
			if c.TopReviewer != "" {
				top = c.TopReviewer + " (" + top + ")"
			}
		}
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", escape(c.Name), num(c.Landed), num(c.Authors), num(c.ReviewerCount),
			top, num(c.ReviewersForHalf), Duration(c.MedianFirstResponseHours), Duration(c.MedianTimeToMergeHours), num(len(c.Waiting)))
	}
	all := allWaiting(res)
	if len(all) == 0 {
		return
	}
	fmt.Fprintf(b, "\n### Waiting for a first response (oldest %d of %d)\n\n", min(waitingListed, len(all)), len(all))
	for _, w := range all[:min(waitingListed, len(all))] {
		by := ""
		if w.Author != "" {
			by = " by " + w.Author
		}
		fmt.Fprintf(b, "- [#%d](%s/%s/pull/%d) %s%s · opened %s · %s\n", w.Number, serverURL, res.Repository, w.Number,
			escape(w.Title), by, w.CreatedAt.Format("2006-01-02"), escape(w.Component))
	}
	fmt.Fprintf(b, "\nOpen PRs with no activity since %s are not in the data, so the oldest unanswered PRs may be missing.\n", res.From)
}

type waiting struct {
	ledger.WaitingPR
	Component string
}

// allWaiting lists every component's waiting pull requests, oldest first, then by number.
func allWaiting(res ledger.Result) []waiting {
	var all []waiting
	for _, c := range res.Components {
		for _, w := range c.Waiting {
			all = append(all, waiting{w, c.Name})
		}
	}
	sort.Slice(all, func(i, j int) bool {
		a, b := all[i], all[j]
		if !a.CreatedAt.Equal(b.CreatedAt) {
			return a.CreatedAt.Before(b.CreatedAt)
		}
		return a.Number < b.Number
	})
	return all
}

func pct(share float64) string { return dec(math.Round(share*1000)/10) + "%" }

// Duration formats hours as hours below two days and days above, as the web page does.
func Duration(h *float64) string {
	switch {
	case h == nil:
		return "–"
	case *h < 48:
		return dec(math.Round(*h*10)/10) + " h"
	default:
		return dec(math.Round(*h/24*10)/10) + " d"
	}
}

// mdEscaper stops untrusted text, such as pull request titles, from rendering as links,
// images, HTML or emphasis, breaking a table, or turning into @mentions and #references.
var mdEscaper = strings.NewReplacer(
	`\`, `\\`, "`", "\\`", "*", `\*`, "_", `\_`, "[", `\[`, "]", `\]`, "(", `\(`, ")", `\)`,
	"<", "&lt;", ">", "&gt;", "!", `\!`, "|", `\|`, "~", `\~`, "@", "@\u2060", "#", "#\u2060")

// escape renders untrusted text as plain inline Markdown on one line.
func escape(s string) string { return mdEscaper.Replace(strings.Join(strings.Fields(s), " ")) }

func dec(f float64) string {
	return strconv.FormatFloat(f, 'f', -1, 64)
}

func num(n int) string {
	s := strconv.Itoa(n)
	if n < 0 {
		return "-" + num(-n)
	}
	for i := len(s) - 3; i > 0; i -= 3 {
		s = s[:i] + "," + s[i:]
	}
	return s
}
